# Generated by Django 3.2.9 on 2021-11-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('fb_link', models.URLField(max_length=255)),
                ('insta_link', models.URLField(max_length=255)),
                ('twitter_link', models.URLField(max_length=255)),
                ('yt_link', models.URLField(max_length=255)),
            ],
        ),
    ]
