# Generated by Django 3.2.9 on 2021-11-25 04:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team_yt_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline1', models.CharField(max_length=255)),
                ('headline2', models.CharField(blank=True, max_length=255)),
                ('photo1', models.ImageField(upload_to='media/about1/%Y/')),
                ('photo2', models.ImageField(upload_to='media/about2/%Y/')),
                ('decription1', ckeditor.fields.RichTextField()),
                ('decription2', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
